=== marcellodesales/svnedge-integration-ctf/ctf/webapp/src/main/resources/META-INF/dtd/sf-api-protocols_1_0.dtd
<!--
@COPYRIGHT
SourceForge(r) Enterprise Edition
Copyright 2007 CollabNet, Inc. All rights reserved.
http://www.collab.net
COPYRIGHT@
-->

<!--
	This DTD must be placed at the following location:
		$CONFIG/dtd/sf-api-protocols_1_0.dtd
	Use the following DOCTYPE statement within an XML document conforming
	to this schema:
	<!DOCTYPE sf-api-protocols
		PUBLIC "-//VA Software, Inc.//DTD API Protocols 1.0//EN"
		"http://www.open.collab.net/sf/dtd/sf-api-protocols_1_0.dtd">
-->

<!ELEMENT  sf-api-protocols     (default-protocol, protocol*)>
<!ELEMENT  default-protocol     (#PCDATA)>
<!ELEMENT  protocol             (protocol-name, protocol-class, config-params?)>
<!ELEMENT  protocol-name        (#PCDATA)>
<!ELEMENT  protocol-class       (#PCDATA)>

<!ELEMENT  config-params	(param*)>
<!ELEMENT  param                (param-name, param-value)>
<!ELEMENT  param-name           (#PCDATA)>
<!ELEMENT  param-value          (#PCDATA)>

=== marcellodesales/svnedge-integration-ctf/ctf/webapp/src/main/webapp/WEB-INF/sf-api-protocols.xml
<?xml version="1.0"?>

<!DOCTYPE sf-api-protocols PUBLIC "-//VA Software, Inc.//DTD API Protocols 1.0//EN"
        "http://schema.vasoftware.com/sf/dtd/sf-api-protocols_1_0.dtd">

<sf-api-protocols>
  <default-protocol>local</default-protocol>
  <protocol>
    <protocol-name>rmi</protocol-name>
    <protocol-class>com.vasoftware.sf.api.RmiProtocol</protocol-class>
    <config-params>
      <param>
        <param-name>java.naming.provider.url</param-name>
        <param-value>localhost</param-value>
      </param>
      <param>
        <param-name>java.naming.factory.url.pkgs</param-name>
        <param-value>org.jboss.naming:org.jnp.interfaces</param-value>
      </param>
      <param>
        <param-name>java.naming.factory.initial</param-name>
        <param-value>org.jnp.interfaces.NamingContextFactory</param-value>
      </param>
    </config-params>
  </protocol>
  <protocol>
    <protocol-name>local</protocol-name>
    <protocol-class>com.vasoftware.sf.api.LocalProtocol</protocol-class>
    <config-params>
      <param>
        <param-name>java.naming.factory.url.pkgs</param-name>
        <param-value>org.jboss.naming:org.jnp.interfaces</param-value>
      </param>
      <param>
        <param-name>java.naming.factory.initial</param-name>
        <param-value>org.jnp.interfaces.NamingContextFactory</param-value>
      </param>
    </config-params>
  </protocol>
</sf-api-protocols>
